version: "3"
services:
  web:
    image: dtr.rlindia.com/praneeta0909/easy-node-authentication:latest
    ports:
    - "9080:9080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
